services:
  mt5-dev:
    build: ./MetaTrader5-Docker-Image/.
    container_name: mt5-dev
    ports:
      - 3010:3000
      - 8010:8001
    networks:
      - app_network_dev

  db-dev:
    image: mysql
    container_name: forex-dev-db
    restart: always
    volumes:
      - /opt/docker-data/dev/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty123
    networks:
      - app_network_dev

  app-dev:
      build:
        context: ./forex-telegram-trade/.  # Build the image using the Dockerfile in the current directory
      container_name: telegram-app-dev
      volumes:
        - /var/log/applog/dev/:/app/logs/  # Mount host directory /var/log/applog to /app/logs for logs
      environment:
        - MT5_SERVER=mt5-dev  # Pass MT5 host from .env or environment variables
        - DB_HOST=forex-dev-db
      depends_on: 
        - mt5-dev
        - forex-dev-db
      entrypoint: /bin/bash -c "/app/wait-for-it.sh mt5-dev:8001 -t 300 -- python main.py"
      networks:
        - app_network_dev

volumes:
  app_logs:  # Named volume for the logs

networks:
  app_network_dev:  # Custom network to enable communication between containers
    driver: bridge  # Use bridge network driver for communication